"""Build the local browser resource bundle; --check verifies reproducibility."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCALES = ROOT / "web" / "locales"


def build() -> str:
    resources = {lang: {"translation": json.loads((LOCALES / f"{lang}.json").read_text(encoding="utf-8"))}
                 for lang in ("en", "de")}
    en, de = (resources[lang]["translation"] for lang in ("en", "de"))
    if set(en) != set(de):
        raise ValueError("English and German translation keys differ")
    for key, text in en.items():
        if not text or not de[key]:
            raise ValueError(f"Empty translation: {key}")
        if sorted(re.findall(r"{{([^}]+)}}", text)) != sorted(re.findall(r"{{([^}]+)}}", de[key])):
            raise ValueError(f"Interpolation mismatch: {key}")
    return "/* Generated by scripts/build_locales.py; edit locales/*.json. */\nwindow.ATLAS_TRANSLATIONS = " + json.dumps(resources, ensure_ascii=False, separators=(",", ":")) + ";\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = LOCALES / "resources.js"
    content = build()
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            raise SystemExit("Translation bundle is stale; run python scripts/build_locales.py")
    else:
        target.write_text(content, encoding="utf-8")
