from __future__ import annotations

from typing import Any

from .config import (
    BATTERY_CHARTS_SOURCE_LABEL,
    EMBER_PRICE_SOURCE_LABEL,
    EMBER_SOURCE_LABEL,
    EUROSTAT_SOURCE_LABEL,
    EUROSTAT_BALANCE_SOURCE_LABEL,
    EUROSTAT_CAPACITY_SOURCE_LABEL,
    EUROSTAT_RETAIL_PRICE_SOURCE_LABEL,
    EUROSTAT_ROAD_SOURCE_LABEL,
    EEA_GHG_SOURCE_LABEL,
    JRC_HYDRO_SOURCE_LABEL,
    JRC_STORAGE_SOURCE_LABEL,
)


from .localization import metric_labels, metric_identities, source_label


def _metric(
    metric_id: str, *, monthly: bool, yearly: bool, snapshot: bool = False,
    table: bool = False, map_view: bool = True, compare: bool = True,
    source: str = EMBER_SOURCE_LABEL, missing: str = "null",
    map_scale: str = "sequential", map_palette: str = "generation",
    map_domain: tuple[float, float] | None = None,
    map_midpoint: float | None = None, map_decimals: int = 2,
    map_latest_available_year: bool = False,
) -> dict[str, Any]:
    labels = metric_labels(metric_id, "en")
    return {
        "id": metric_id, **labels,
        "label_en": labels["label"],
        "label_de": metric_labels(metric_id, "de")["label"],
        **metric_identities()[metric_id],
        "views": [view for view, enabled in (("table", table), ("map", map_view), ("compare", compare)) if enabled],
        "temporal_availability": {"monthly": monthly, "yearly": yearly, "snapshot": snapshot},
        "sortable": True, "table": table, "map": map_view, "compare": compare,
        "source": source_label(source), "missing_value": missing,
        "map_config": {
            "scale": map_scale, "palette": map_palette,
            "domain": list(map_domain) if map_domain else None,
            "midpoint": map_midpoint, "decimals": map_decimals,
            "latest_available_year": map_latest_available_year,
        },
    }


METRICS: tuple[dict[str, Any], ...] = (
    _metric("generation_twh", monthly=True, yearly=True, table=True),
    _metric("consumption_twh", monthly=True, yearly=True, table=True, map_palette='consumption'),
    _metric("generation_per_capita_mwh", monthly=False, yearly=True),
    _metric("consumption_per_capita_mwh", monthly=False, yearly=True, table=True, source=f'{EMBER_SOURCE_LABEL}; {EUROSTAT_SOURCE_LABEL}', map_palette='consumption'),
    _metric("low_carbon_share_pct", monthly=True, yearly=True, map_palette='renewables', map_decimals=1),
    _metric("self_sufficiency_pct", monthly=True, yearly=True, map_palette='consumption', map_decimals=1),
    _metric("renewable_twh", monthly=True, yearly=True, map_palette='renewables'),
    _metric("renewable_share_pct", monthly=True, yearly=True, table=True, map_palette='renewables', map_decimals=1),
    _metric("renewable_per_capita_mwh", monthly=False, yearly=True, source=f'{EMBER_SOURCE_LABEL}; {EUROSTAT_SOURCE_LABEL}', map_palette='renewables'),
    _metric("wind_twh", monthly=True, yearly=True, map_palette='wind'),
    _metric("wind_share_pct", monthly=True, yearly=True, map_palette='wind', map_decimals=1),
    _metric("wind_per_capita_mwh", monthly=False, yearly=True, source=f'{EMBER_SOURCE_LABEL}; {EUROSTAT_SOURCE_LABEL}', map_palette='wind'),
    _metric("solar_twh", monthly=True, yearly=True, map_palette='solar'),
    _metric("solar_share_pct", monthly=True, yearly=True, map_palette='solar', map_decimals=1),
    _metric("solar_per_capita_mwh", monthly=False, yearly=True, source=f'{EMBER_SOURCE_LABEL}; {EUROSTAT_SOURCE_LABEL}', map_palette='solar'),
    _metric("hydro_twh", monthly=True, yearly=True, map_palette='hydro'),
    _metric("hydro_share_pct", monthly=True, yearly=True, map_palette='hydro', map_decimals=1),
    _metric("hydro_per_capita_mwh", monthly=False, yearly=True, source=f'{EMBER_SOURCE_LABEL}; {EUROSTAT_SOURCE_LABEL}', map_palette='hydro'),
    _metric("bioenergy_twh", monthly=True, yearly=True, map_palette='bioenergy'),
    _metric("bioenergy_share_pct", monthly=True, yearly=True, map_palette='bioenergy', map_decimals=1),
    _metric("bioenergy_per_capita_mwh", monthly=False, yearly=True, source=f'{EMBER_SOURCE_LABEL}; {EUROSTAT_SOURCE_LABEL}', map_palette='bioenergy'),
    _metric("other_renewables_twh", monthly=True, yearly=True, map_palette='other-renewables'),
    _metric("other_renewables_share_pct", monthly=True, yearly=True, map_palette='other-renewables', map_decimals=1),
    _metric("other_renewables_per_capita_mwh", monthly=False, yearly=True, source=f'{EMBER_SOURCE_LABEL}; {EUROSTAT_SOURCE_LABEL}', map_palette='other-renewables'),
    _metric("fossil_twh", monthly=True, yearly=True, map_palette='fossil'),
    _metric("fossil_share_pct", monthly=True, yearly=True, table=True, map_palette='fossil', map_decimals=1),
    _metric("fossil_per_capita_mwh", monthly=False, yearly=True, source=f'{EMBER_SOURCE_LABEL}; {EUROSTAT_SOURCE_LABEL}', map_palette='fossil'),
    _metric("coal_twh", monthly=True, yearly=True, map_palette='coal'),
    _metric("coal_share_pct", monthly=True, yearly=True, map_palette='coal', map_decimals=1),
    _metric("coal_per_capita_mwh", monthly=False, yearly=True, source=f'{EMBER_SOURCE_LABEL}; {EUROSTAT_SOURCE_LABEL}', map_palette='coal'),
    _metric("gas_twh", monthly=True, yearly=True, map_palette='gas'),
    _metric("gas_share_pct", monthly=True, yearly=True, map_palette='gas', map_decimals=1),
    _metric("gas_per_capita_mwh", monthly=False, yearly=True, source=f'{EMBER_SOURCE_LABEL}; {EUROSTAT_SOURCE_LABEL}', map_palette='gas'),
    _metric("other_fossil_twh", monthly=True, yearly=True, map_palette='other-fossil'),
    _metric("other_fossil_share_pct", monthly=True, yearly=True, map_palette='other-fossil', map_decimals=1),
    _metric("other_fossil_per_capita_mwh", monthly=False, yearly=True, source=f'{EMBER_SOURCE_LABEL}; {EUROSTAT_SOURCE_LABEL}', map_palette='other-fossil'),
    _metric("nuclear_twh", monthly=True, yearly=True, map_palette='nuclear'),
    _metric("nuclear_share_pct", monthly=True, yearly=True, table=True, map_palette='nuclear', map_decimals=1),
    _metric("nuclear_per_capita_mwh", monthly=False, yearly=True, source=f'{EMBER_SOURCE_LABEL}; {EUROSTAT_SOURCE_LABEL}', map_palette='nuclear'),
    _metric("net_imports_twh", monthly=True, yearly=True, map_scale='diverging', map_palette='trade', map_midpoint=0),
    _metric("net_import_share_pct", monthly=True, yearly=True, table=True, map_scale='diverging', map_palette='trade', map_midpoint=0, map_decimals=1),
    _metric("price_avg_eur_mwh", monthly=True, yearly=True, table=True, source=EMBER_PRICE_SOURCE_LABEL, map_palette='price'),
    _metric("carbon_intensity_gco2eq_kwh", monthly=True, yearly=True, table=True, map_palette='carbon', map_decimals=0),
    _metric("estimated_generation_emissions_mtco2eq", monthly=True, yearly=True, map_palette='carbon', map_decimals=2),
    _metric("decarbonization_rate_pct", monthly=False, yearly=True, map_scale='diverging', map_palette='carbon', map_midpoint=0, map_decimals=1),
    _metric("eea_public_electricity_heat_emissions_mtco2eq", monthly=False, yearly=True, source=EEA_GHG_SOURCE_LABEL, map_palette='carbon'),
    _metric("population", monthly=False, yearly=True, source=EUROSTAT_SOURCE_LABEL, map_palette='population', map_decimals=0),
    _metric("gdp_current_billion_eur", monthly=False, yearly=True, source=EUROSTAT_SOURCE_LABEL, map_palette='gdp'),
    _metric("gdp_per_capita_pps", monthly=False, yearly=True, source=EUROSTAT_SOURCE_LABEL, map_palette='gdp-per-capita', map_decimals=0),
    _metric("generation_gdp_intensity_kwh_eur", monthly=False, yearly=True, source=f'{EMBER_SOURCE_LABEL}; {EUROSTAT_SOURCE_LABEL}', map_palette='generation', map_decimals=3),
    _metric("consumption_gdp_intensity_kwh_eur", monthly=False, yearly=True, source=f'{EMBER_SOURCE_LABEL}; {EUROSTAT_SOURCE_LABEL}', map_palette='consumption', map_decimals=3),
    _metric("electricity_heat_emissions_gdp_t_million_eur", monthly=False, yearly=True, source=f'{EEA_GHG_SOURCE_LABEL}; {EUROSTAT_SOURCE_LABEL}', map_palette='carbon', map_decimals=1, map_latest_available_year=True),
    _metric("capacity_total_gw", monthly=False, yearly=True, source=EUROSTAT_CAPACITY_SOURCE_LABEL, map_palette='generation', map_latest_available_year=True),
    _metric("capacity_wind_gw", monthly=False, yearly=True, source=EUROSTAT_CAPACITY_SOURCE_LABEL, map_palette='wind', map_latest_available_year=True),
    _metric("capacity_solar_gw", monthly=False, yearly=True, source=EUROSTAT_CAPACITY_SOURCE_LABEL, map_palette='solar', map_latest_available_year=True),
    _metric("capacity_hydro_gw", monthly=False, yearly=True, source=EUROSTAT_CAPACITY_SOURCE_LABEL, map_palette='hydro', map_latest_available_year=True),
    _metric("capacity_fossil_gw", monthly=False, yearly=True, source=EUROSTAT_CAPACITY_SOURCE_LABEL, map_palette='fossil', map_latest_available_year=True),
    _metric("capacity_nuclear_gw", monthly=False, yearly=True, source=EUROSTAT_CAPACITY_SOURCE_LABEL, map_palette='nuclear', map_latest_available_year=True),
    _metric("capacity_factor_wind_pct", monthly=False, yearly=True, source=f'{EMBER_SOURCE_LABEL}; {EUROSTAT_CAPACITY_SOURCE_LABEL}', map_palette='wind', map_decimals=1),
    _metric("capacity_factor_solar_pct", monthly=False, yearly=True, source=f'{EMBER_SOURCE_LABEL}; {EUROSTAT_CAPACITY_SOURCE_LABEL}', map_palette='solar', map_decimals=1),
    _metric("capacity_factor_hydro_pct", monthly=False, yearly=True, source=f'{EMBER_SOURCE_LABEL}; {EUROSTAT_CAPACITY_SOURCE_LABEL}', map_palette='hydro', map_decimals=1),
    _metric("capacity_factor_fossil_pct", monthly=False, yearly=True, source=f'{EMBER_SOURCE_LABEL}; {EUROSTAT_CAPACITY_SOURCE_LABEL}', map_palette='fossil', map_decimals=1),
    _metric("capacity_factor_nuclear_pct", monthly=False, yearly=True, source=f'{EMBER_SOURCE_LABEL}; {EUROSTAT_CAPACITY_SOURCE_LABEL}', map_palette='nuclear', map_decimals=1),
    _metric("household_electricity_price_eur_mwh", monthly=False, yearly=True, source=EUROSTAT_RETAIL_PRICE_SOURCE_LABEL, map_palette='price'),
    _metric("household_price_energy_eur_mwh", monthly=False, yearly=True, source=EUROSTAT_RETAIL_PRICE_SOURCE_LABEL, map_palette='price'),
    _metric("household_price_network_eur_mwh", monthly=False, yearly=True, source=EUROSTAT_RETAIL_PRICE_SOURCE_LABEL, map_palette='price'),
    _metric("household_price_taxes_eur_mwh", monthly=False, yearly=True, source=EUROSTAT_RETAIL_PRICE_SOURCE_LABEL, map_palette='price'),
    _metric("household_wholesale_price_gap_ct_kwh", monthly=False, yearly=True, source=f'{EUROSTAT_RETAIL_PRICE_SOURCE_LABEL}; {EMBER_PRICE_SOURCE_LABEL}', map_palette='price', map_decimals=2),
    _metric("nonhousehold_electricity_price_eur_mwh", monthly=False, yearly=True, source=EUROSTAT_RETAIL_PRICE_SOURCE_LABEL, map_palette='price'),
    _metric("nonhousehold_price_energy_eur_mwh", monthly=False, yearly=True, source=EUROSTAT_RETAIL_PRICE_SOURCE_LABEL, map_palette='price'),
    _metric("nonhousehold_price_network_eur_mwh", monthly=False, yearly=True, source=EUROSTAT_RETAIL_PRICE_SOURCE_LABEL, map_palette='price'),
    _metric("nonhousehold_price_taxes_eur_mwh", monthly=False, yearly=True, source=EUROSTAT_RETAIL_PRICE_SOURCE_LABEL, map_palette='price'),
    _metric("gross_imports_twh", monthly=False, yearly=True, source=EUROSTAT_BALANCE_SOURCE_LABEL, map_palette='trade'),
    _metric("gross_exports_twh", monthly=False, yearly=True, source=EUROSTAT_BALANCE_SOURCE_LABEL, map_palette='trade'),
    _metric("electricity_trade_throughput_pct", monthly=False, yearly=True, source=f'{EUROSTAT_BALANCE_SOURCE_LABEL}; {EMBER_SOURCE_LABEL}', map_palette='trade', map_decimals=1),
    _metric("bev_stock", monthly=False, yearly=True, source=EUROSTAT_ROAD_SOURCE_LABEL, map_palette='battery', map_decimals=0),
    _metric("bev_new_registrations", monthly=False, yearly=True, source=EUROSTAT_ROAD_SOURCE_LABEL, map_palette='battery', map_decimals=0),
    _metric("ev_battery_nominal_capacity_est_gwh", monthly=False, yearly=True, source=EUROSTAT_ROAD_SOURCE_LABEL, map_palette='battery'),
    _metric("hydro_plant_capacity_gw", monthly=False, yearly=False, snapshot=True, compare=False, source=JRC_HYDRO_SOURCE_LABEL, map_palette='hydro'),
    _metric("hydro_pumping_power_gw", monthly=False, yearly=False, snapshot=True, compare=False, source=JRC_HYDRO_SOURCE_LABEL, map_palette='hydro'),
    _metric("hydro_reservoir_energy_gwh", monthly=False, yearly=False, snapshot=True, compare=False, source=JRC_HYDRO_SOURCE_LABEL, map_palette='hydro'),
    _metric("battery_power_gw", monthly=False, yearly=False, snapshot=True, source=f'{BATTERY_CHARTS_SOURCE_LABEL}; {JRC_STORAGE_SOURCE_LABEL}', map_palette='battery'),
    _metric("battery_energy_gwh", monthly=False, yearly=False, snapshot=True, source=f'{BATTERY_CHARTS_SOURCE_LABEL}; {JRC_STORAGE_SOURCE_LABEL}', map_palette='battery'),
    _metric("battery_duration_hours", monthly=False, yearly=False, snapshot=True, source=f'{BATTERY_CHARTS_SOURCE_LABEL}; {JRC_STORAGE_SOURCE_LABEL}', map_palette='battery'),
    _metric("pumped_storage_power_gw", monthly=False, yearly=False, snapshot=True, source=JRC_STORAGE_SOURCE_LABEL, map_palette='pumped-storage'),
    _metric("pumped_storage_energy_gwh", monthly=False, yearly=False, snapshot=True, source=JRC_STORAGE_SOURCE_LABEL, map_palette='pumped-storage'),
    _metric("pumped_storage_duration_hours", monthly=False, yearly=False, snapshot=True, source=JRC_STORAGE_SOURCE_LABEL, map_palette='pumped-storage'),
)

METRICS_BY_ID = {metric["id"]: metric for metric in METRICS}


def metric_catalog(language: str = "de") -> list[dict[str, Any]]:
    """Legacy German presentation by default; identifiers never depend on language."""
    return [{**metric, **metric_labels(metric["id"], language), "source": source_label(metric["source"], language)} for metric in METRICS]
